import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.DevelopmentalBiologyMorphogenesisCanonicalLaneLean.GeneRegulatoryNetwork
import HautevilleHouse.DevelopmentalBiologyMorphogenesisCanonicalLaneLean.MorphogenGradient
import HautevilleHouse.DevelopmentalBiologyMorphogenesisCanonicalLaneLean.SegmentationClock
import HautevilleHouse.DevelopmentalBiologyMorphogenesisCanonicalLaneLean.CellFateSpecification
import HautevilleHouse.DevelopmentalBiologyMorphogenesisCanonicalLaneLean.TissueMorphodynamics

namespace HautevilleHouse
namespace DevelopmentalBiologyMorphogenesisCanonicalLaneLean

def ConstrainedMorphogenesisClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_morphogenesis_endgame (A : AdmissibleClass) :
    ConstrainedMorphogenesisClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end DevelopmentalBiologyMorphogenesisCanonicalLaneLean
end HautevilleHouse